(chore) kubereplay fork v1 - works on AKS 1.16
loggi/kubereplay pull request #1
Opened 2021-02-10 20:44 UTC by diegopedroso1

This PR includes a lot of things (including CRDs) to deploy Kubereplay on AKS 1.16+. All Setups include our files to deploy tests on the Loggi-Web environment.

2021-02-10 20:56 UTC, matheusgiuliano approved these changes

2021-02-10 20:57 UTC, danielsousa8 approved these changes

2021-02-11 12:58 UTC, azlev requested changes

2021-02-11 12:58 UTC, azlev commented on README.md
> +# Kubereplay
Before we proceed the merge, I want to talk about some points here.

The code above, in the `Makefile` is clearly something that we can contribute to the community if we are willing to do it (and we are).

On the other hand, this `README.md` now contains references to our projects and was written in portuguese.

I propose to keep the inserted content of this doc in https://loggidev.atlassian.net/wiki/spaces/DEVOPS/pages/1922957410/LW+Split+DB+tests+with+Goreplay and leave the `README.md` just to document the tool.

Let's keep the tool related commits in this repo (fixes in the code) and project related information in confluence.

2021-02-11 12:58 UTC, azlev commented on sample/harvester.yaml
> +  name: harvester-corp
As you explained in Slack / daily, this code will leave in a different branch as the master. So it's wiser to split this in another commit and keep it separated from master:

```
            E--F private-branch
           /
  A---B---C master-with-fixes
 /
D master
```
Every time that we fix something, we add it in the `master-with-fixes` and `merge` / `rebase` the `private-branch`

2021-02-11 12:58 UTC, azlev commented on vendor/github.com/go-openapi/spec/bindata.go
> +	"v2/schema.json": v2SchemaJSON,
Those changes inside `vendor` were unexpected. Do we need to keep the vendor code commited? I never read about `dep`, but it's important to check this, maybe this is not a best practice.

2021-02-12 21:52 UTC, merged